# Generated by Django 4.0.3 on 2022-04-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_Descripcion_Nulleable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='fecha_caducidad',
            new_name='fechaCaducidad',
        ),
        migrations.AddField(
            model_name='tareas',
            name='foto',
            field=models.ImageField(null=True, upload_to='multimedia'),
        ),
    ]
